// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7V8p0rFUPqhUkG2TqC0x2UvYg7DBNTVE',
    appId: '1:383826597233:web:9c72e6dba07243c6a152d0',
    messagingSenderId: '383826597233',
    projectId: 'myportfolio-fad23',
    authDomain: 'myportfolio-fad23.firebaseapp.com',
    storageBucket: 'myportfolio-fad23.firebasestorage.app',
    measurementId: 'G-XKDKXE64S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8D9moPmFc35yHp6fUQUX1XPnkiNwh-PM',
    appId: '1:383826597233:android:93204143915f09c2a152d0',
    messagingSenderId: '383826597233',
    projectId: 'myportfolio-fad23',
    storageBucket: 'myportfolio-fad23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRhbiRXJYFweU-Fa29vNSphZ1c7nE3n0',
    appId: '1:383826597233:ios:95f048a2cdfb88c9a152d0',
    messagingSenderId: '383826597233',
    projectId: 'myportfolio-fad23',
    storageBucket: 'myportfolio-fad23.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdRhbiRXJYFweU-Fa29vNSphZ1c7nE3n0',
    appId: '1:383826597233:ios:95f048a2cdfb88c9a152d0',
    messagingSenderId: '383826597233',
    projectId: 'myportfolio-fad23',
    storageBucket: 'myportfolio-fad23.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7V8p0rFUPqhUkG2TqC0x2UvYg7DBNTVE',
    appId: '1:383826597233:web:e99c96e191f3fb8da152d0',
    messagingSenderId: '383826597233',
    projectId: 'myportfolio-fad23',
    authDomain: 'myportfolio-fad23.firebaseapp.com',
    storageBucket: 'myportfolio-fad23.firebasestorage.app',
    measurementId: 'G-JHE25LHLGY',
  );
}
